SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.AMOUNT*P.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT P , FOOD_ORDER O
WHERE 1=1
 AND P.PRODUCT_ID = O.PRODUCT_ID
 AND EXTRACT(MONTH FROM O.PRODUCE_DATE) = '5'
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID;